require 'open-uri'

PROJECT_DIR = File.dirname(__FILE__)
JAR_DIR = File.join(PROJECT_DIR, 'jars')
directory JAR_DIR

def get_maven_jar_info(group_id, artifact_id, version)
  jar_name = "#{artifact_id}-#{version}.jar"
  jar_url = "http://repo1.maven.org/maven2/#{group_id.gsub(/\./, '/')}/#{artifact_id}/#{version}/#{jar_name}"
  local_jar_file = File.join(JAR_DIR, jar_name)
  [jar_name, jar_url, local_jar_file]
end

def download_maven_jar(group_id, artifact_id, version)
  jar_name, jar_url, local_jar_file = get_maven_jar_info(group_id, artifact_id, version)
  open(jar_url) do |remote_jar|
    open(local_jar_file, 'w') do |local_jar|
      IO.copy_stream(remote_jar, local_jar)
    end
  end
end

MAVEN_PACKAGES = [
  # (group id, artifact id, version),
  ['com.amazonaws', 'amazon-kinesis-client', '1.2.0'],
  ['com.fasterxml.jackson.core', 'jackson-core', '2.1.1'],
  ['org.apache.httpcomponents', 'httpclient', '4.2'],
  ['org.apache.httpcomponents', 'httpcore', '4.2'],
  ['com.fasterxml.jackson.core', 'jackson-annotations', '2.1.1'],
  ['commons-codec', 'commons-codec', '1.3'],
  ['joda-time', 'joda-time', '2.4'],
  ['com.amazonaws', 'aws-java-sdk', '1.7.13'],
  ['com.fasterxml.jackson.core', 'jackson-databind', '2.1.1'],
  ['commons-logging', 'commons-logging', '1.1.1'],
]

task :download_jars => [JAR_DIR]

MAVEN_PACKAGES.each do |jar|
  _, _, local_jar_file = get_maven_jar_info(*jar)
  file local_jar_file do
    puts "Downloading '#{local_jar_file}' from maven..."
    download_maven_jar(*jar)
  end
  task :download_jars => local_jar_file
end

desc "Run KCL producer to generate data"
task :run_producer do |t|
  puts "Running the Kinesis producer application..."
  commands = %W(
    bundle exec ruby #{PROJECT_DIR}/producer/kcl_producer.rb
  )
  sh *commands
end

desc "Run KCL processor"
task :run => :download_jars do |t|
  puts "Running the Kinesis processing application..."
  classpath = FileList["#{JAR_DIR}/*.jar"].join(':')
  classpath += ":#{PROJECT_DIR}"
  ENV['PATH'] = "#{ENV['PATH']}:#{PROJECT_DIR}"
  commands = %W(
    java
    -classpath #{classpath}
    com.amazonaws.services.kinesis.multilang.MultiLangDaemon client/sample.properties
  )
  sh *commands
end

desc "Show Kinesis stream shard info"
task :show_shard_info do
  commands = %W(
    bundle exec ruby #{PROJECT_DIR}/manager/kcl_shard_info.rb
  )
  sh *commands
end

desc "Split Kinesis stream shard"
task :split_shard do
  commands = %W(
    bundle exec ruby #{PROJECT_DIR}/manager/kcl_split_shard.rb
  )
  sh *commands
end
